package Curso::Model::DVD;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Curso::Schema::DVDRental',
    
    connect_info => {
        dsn => 'dbi:Pg:database=dvdrental;host=127.0.0.1',
        user => 'curso',
        password => 'curso',
        pg_enable_utf8  => q{ 1},
    }
);

=head1 NAME

Curso::Model::DVD - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Curso>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Curso::Schema::DVDRental>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Juan Paredes

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
